[".config/base16-shell"]
type = "git-repo"
url = "https://github.com/chriskempson/base16-shell.git"

[".config/qmk"]
type = "git-repo"
url = "https://github.com/qmk/qmk_firmware.git"
refreshPeriod = "1m"
[".config/qmk".clone]
args = ["--recurse-submodules"]
[".config/qmk".pull]
args = ["--recurse-submodules"]

[".config/qmk_userspace"]
type = "git-repo"
url = "https://github.com/kvndrsslr/qmk_userspace.git"
refreshPeriod = "1m"
