set-option -g default-shell /usr/local/bin/zsh

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'kvndrsslr/tmux-gruvbox-base16-256'

# set -g default-command  "zsh"

# Custom prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Resurrect Settings
# set -g @resurrect-processes '~mc man vim newsboat htop'
# set -g @resurrect-strategy-vim 'session'

# Continuum Settings
set -g @continuum-boot 'off'
set -g @continuum-restore 'off'

# force a reload of the config file
unbind r
bind r source-file ~/.tmux.conf

# quick pane cycling
unbind ^A
bind ^A select-pane -t :.+

# start copy mode scrolling 1 page up and exit copy mode upon scrolling beyond the last line
unbind [
bind [ copy-mode -eu

# Watch background windows for activity
setw -g monitor-activity on
set -g visual-activity off

# set proper terminfo
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:RGB"

# other settings
set-window-option -g mode-keys vi
set -g mouse on
set-option -g history-limit 131072 # 2^17

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Initializes TMUX plugin manager.
# Keep this line at the very bottom of tmux.conf.
run -b '~/.tmux/plugins/tpm/tpm'
