# ~/.ticker.yaml
show-summary: true
show-tags: true
show-fundamentals: true
show-separator: true
show-holdings: true
interval: 1
sort: user
currency: EUR
watchlist:
  - GME
  - AMC
  - SLGG
  - DOGE-USD
  - BTC-USD
lots:
  - symbol: "AMC"
    quantity: 540.0
    unit_cost: 54.739896
  - symbol: "GME"
    quantity: 0.0
    unit_cost: 257.09768
colors:
  text: "#fbf1c7"
  text-light: "#a89984"
  text-label: "#d5c4a1"
  text-line: "#504945"
  text-tag: "#b8bb26"
  background-tag: "#3c3836"
